# .goreleaser.yml for comfy-chair-go
project_name: comfy-chair
builds:
  - id: comfy-chair
    main: .
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - README.md
      - LICENSE
      - .env.example
      - comfy-installs.json
      - templates/**/*
      - demos/**/*
checksum:
  name_template: "checksums.txt"
release:
  github:
    owner: regiellis
    name: comfy-chair-go