version: '3'

vars:
  BIN_NAME: comfy-chair
  DIST_DIR: dist
  SOURCES: '**/*.go'
  TARGETS:
    - { os: linux,   arch: amd64, ext: '' }
    - { os: darwin,  arch: amd64, ext: '' }
    - { os: windows, arch: amd64, ext: '.exe' }

tasks:
  build:
    desc: Build the comfy-chair binary for your OS/arch
    cmds:
      - go build -o {{.BIN_NAME}} .
    sources:
      - '{{.SOURCES}}'
    generates:
      - '{{.BIN_NAME}}'

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BIN_NAME}}
      - rm -rf {{.DIST_DIR}}

  install:
    desc: Install comfy-chair to your $GOBIN or $GOPATH/bin
    cmds:
      - go install .

  run:
    desc: Run the comfy-chair CLI
    cmds:
      - ./{{.BIN_NAME}}

  build-all:
    desc: Build comfy-chair for multiple OS/arch targets
    cmds:
      - |
        mkdir -p {{.DIST_DIR}}
        for target in "linux amd64 ''" "darwin amd64 ''" "windows amd64 .exe"; do
          set -- $target
          GOOS=$1 GOARCH=$2 go build -o {{.DIST_DIR}}/{{.BIN_NAME}}-$1-$2$3 .
        done
    sources:
      - '{{.SOURCES}}'
    generates:
      - '{{.DIST_DIR}}/{{.BIN_NAME}}-linux-amd64'
      - '{{.DIST_DIR}}/{{.BIN_NAME}}-darwin-amd64'
      - '{{.DIST_DIR}}/{{.BIN_NAME}}-windows-amd64.exe'

  build-dev:
    desc: Build comfy-chair for development with debug symbols
    cmds:
      - go build -gcflags="all=-N -l" -o {{.BIN_NAME}} .
    sources:
      - '{{.SOURCES}}'
    generates:
      - '{{.BIN_NAME}}'
