version: '3'

tasks:
  build:
    desc: Build the comfy-chair binary for your OS/arch
    cmds:
      - go build -o comfy-chair main.go nodes.go reload.go styles.go procattr_unix.go procattr_windows.go
    sources:
      - '**/*.go'
    generates:
      - comfy-chair

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f comfy-chair
      - rm -rf dist

  install:
    desc: Install comfy-chair to your $GOBIN or $GOPATH/bin
    cmds:
      - go install ./...

  run:
    desc: Run the comfy-chair CLI
    cmds:
      - ./comfy-chair

  build-all:
    desc: Build comfy-chair for multiple OS/arch targets
    cmds:
      - GOOS=linux   GOARCH=amd64 go build -o dist/comfy-chair-linux-amd64   main.go nodes.go reload.go styles.go procattr_unix.go procattr_windows.go
      - GOOS=darwin  GOARCH=amd64 go build -o dist/comfy-chair-darwin-amd64  main.go nodes.go reload.go styles.go procattr_unix.go procattr_windows.go
      - GOOS=windows GOARCH=amd64 go build -o dist/comfy-chair-windows-amd64.exe main.go nodes.go reload.go styles.go procattr_unix.go procattr_windows.go
    sources:
      - '**/*.go'
    generates:
      - dist/comfy-chair-linux-amd64
      - dist/comfy-chair-darwin-amd64
      - dist/comfy-chair-windows-amd64.exe

  build-dev:
    desc: Build comfy-chair for development with debug symbols
    cmds:
      - GOOS=linux go build -gcflags="all=-N -l" -o comfy-chair main.go nodes.go reload.go styles.go procattr_unix.go
    sources:
      - '**/*.go'
    generates:
      - comfy-chair
