name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build all binaries (cross-platform)
        run: |
          mkdir -p dist
          GOOS=linux   GOARCH=amd64 go build -o dist/comfy-chair-linux-amd64   .
          GOOS=darwin  GOARCH=amd64 go build -o dist/comfy-chair-darwin-amd64  .
          GOOS=windows GOARCH=amd64 go build -o dist/comfy-chair-windows-amd64.exe .

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/*

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
